// End-to-end Phase 6 done-bar: loads the actual checked-in dummy ONNX model (generated by
// generate_dummy_model.py from the same policy_adapter.yaml DummyAdapter reads), runs shape
// validation, performs real inference, and decodes an action - all deterministic and
// reproducible, per IMPLEMENTATION_PLAN.md S3 Phase 6.
#include <cmath>
#include <numeric>
#include <string>

#include "gtest/gtest.h"

#include "crowd_nav_policy_adapters/candidate_action_space.hpp"
#include "crowd_nav_policy_adapters/dummy_adapter.hpp"
#include "crowd_nav_policy_adapters/onnx_inference.hpp"
#include "crowd_nav_policy_adapters/shape_validation.hpp"

using crowd_nav_observation::WorldState;
using crowd_nav_perception::HumanObservation;
using crowd_nav_policy_adapters::CandidateActionSpaceConfig;
using crowd_nav_policy_adapters::DummyAdapter;
using crowd_nav_policy_adapters::loadCandidateActionSpaceConfig;
using crowd_nav_policy_adapters::runInference;
using crowd_nav_policy_adapters::validateSessionShapes;

namespace
{
std::string packageDir() {return CROWD_NAV_POLICY_ADAPTERS_PACKAGE_DIR;}

WorldState makeSyntheticState()
{
  WorldState state;
  // Robot at the origin, goal straight ahead in +y - desired heading pi/2, chosen specifically
  // NOT near 0 so it can't tie with the stop action's degenerate atan2(0,0)==0 heading.
  state.robot = {0.0, 0.0, 0.0, 0.0, 0.14, 0.0, 10.0, 1.0, 0.0};

  HumanObservation h1;
  h1.id = 1;
  h1.x = 2.0;
  h1.y = 1.0;
  h1.vx = 0.1;
  h1.vy = 0.0;
  state.humans.push_back(h1);

  HumanObservation h2;
  h2.id = 2;
  h2.x = -1.0;
  h2.y = 3.0;
  h2.vx = 0.0;
  h2.vy = -0.2;
  state.humans.push_back(h2);

  return state;
}
}  // namespace

TEST(DummyAdapterEndToEnd, LoadsShapeValidatesInfersAndDecodesDeterministically)
{
  const CandidateActionSpaceConfig config =
    loadCandidateActionSpaceConfig(packageDir() + "/config/policy_adapter.yaml");
  DummyAdapter adapter(config);

  const WorldState state = makeSyntheticState();
  const auto inputs = adapter.buildInputs(state);
  ASSERT_EQ(inputs.names.size(), 1u);
  ASSERT_EQ(inputs.shapes[0].size(), 2u);
  EXPECT_EQ(inputs.shapes[0][0], static_cast<int64_t>(config.candidateCount()));
  EXPECT_EQ(inputs.shapes[0][1], static_cast<int64_t>(config.featureDim()));

  // Known-correct expected output per row (trivial model is weight=1, bias=0 -> sum(row)),
  // computed here independently of the ONNX session.
  const size_t n = static_cast<size_t>(inputs.shapes[0][0]);
  const size_t f = static_cast<size_t>(inputs.shapes[0][1]);
  std::vector<float> expected_sums(n, 0.0f);
  for (size_t row = 0; row < n; ++row) {
    expected_sums[row] = std::accumulate(
      inputs.data[0].begin() + row * f, inputs.data[0].begin() + (row + 1) * f, 0.0f);
  }

  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test_dummy_adapter");
  Ort::SessionOptions options;
  Ort::Session session(env, (packageDir() + "/models/dummy_policy.onnx").c_str(), options);

  ASSERT_NO_THROW(validateSessionShapes(session, adapter.expectedShape()));

  const auto outputs = runInference(session, inputs, {"value"});
  ASSERT_EQ(outputs.data.size(), 1u);
  ASSERT_EQ(outputs.data[0].size(), n);
  for (size_t row = 0; row < n; ++row) {
    EXPECT_NEAR(outputs.data[0][row], expected_sums[row], 1e-2f) << "row " << row;
  }

  const auto cmd = adapter.selectAction(outputs, state);
  // Independently computed (Python, not this project's C++ formula) best candidate for a
  // straight-ahead-in-+y goal with this action-space config: rotation index 4 (pi/2 exactly),
  // smallest speed sample - candidate index 1 + 4*5 + 0 = 21.
  EXPECT_NEAR(cmd.vx, 0.0, 1e-9);
  EXPECT_NEAR(cmd.vy, 0.12885124808584156, 1e-9);
}

TEST(DummyAdapterEndToEnd, DoesNotStopWhenGoalIsRoughlyAheadOfTheRobot)
{
  // Regression test for a real bug found live in Phase 7 (docs/phase7-findings.md): the stop
  // action's degenerate atan2(0,0)==0 heading used to tie with the goal-ahead case (the COMMON
  // case, not an edge case) and win, leaving the robot permanently stopped. Goal directly ahead
  // (+x, matching the robot's initial theta=0) is exactly that case.
  const CandidateActionSpaceConfig config =
    loadCandidateActionSpaceConfig(packageDir() + "/config/policy_adapter.yaml");
  DummyAdapter adapter(config);

  WorldState state;
  state.robot = {0.0, 0.0, 0.0, 0.0, 0.14, 5.0, 0.0, 1.0, 0.0};  // goal (5,0): straight ahead

  const auto inputs = adapter.buildInputs(state);
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test_dummy_adapter_goal_ahead");
  Ort::SessionOptions options;
  Ort::Session session(env, (packageDir() + "/models/dummy_policy.onnx").c_str(), options);
  const auto outputs = runInference(session, inputs, {"value"});

  const auto cmd = adapter.selectAction(outputs, state);
  EXPECT_GT(std::hypot(cmd.vx, cmd.vy), 0.01) << "must drive toward the goal, not stay stopped";
}

TEST(DummyAdapterEndToEnd, RepeatedCallsAreDeterministic)
{
  const CandidateActionSpaceConfig config =
    loadCandidateActionSpaceConfig(packageDir() + "/config/policy_adapter.yaml");
  DummyAdapter adapter_a(config);
  DummyAdapter adapter_b(config);

  const WorldState state = makeSyntheticState();
  const auto inputs_a = adapter_a.buildInputs(state);
  const auto inputs_b = adapter_b.buildInputs(state);

  ASSERT_EQ(inputs_a.data[0].size(), inputs_b.data[0].size());
  for (size_t i = 0; i < inputs_a.data[0].size(); ++i) {
    EXPECT_FLOAT_EQ(inputs_a.data[0][i], inputs_b.data[0][i]);
  }
}
